# Generated by Django 5.2.6 on 2025-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='solution',
            field=models.CharField(max_length=81, null=True),
        ),
    ]
