services:
  sophia_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sophia_image
    container_name: sophia_container
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
  
  proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/static:ro
    depends_on:
      - sophia_app